#-------------------------------
# General Site Settings
title: Poi's House
logo: logo.svg # You can add own logo.
description: Just some random stuff of my life...


#-------------------------------
# Author Settings
author:
  name: Poi Wang
  image: 01.jpg
  say-hello: Hello, I’m <strong>Poi Wang</strong>
  bio: Finance. Business Analysis. Daydreamer.

#-------------------------------
# Contact links
twitter: https://twitter.com/poi_0905 # Add your Twitter handle
facebook: https://facebook.com/profile.php?id=100000584444686 # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/poi_0905 # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: poi0905 # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
